name       : swtpm
version    : 0.7.1
release    : 5
source     :
    - https://github.com/stefanberger/swtpm/archive/refs/tags/v0.7.1.tar.gz : 94de2abb6fed3645e095c05012f274d1e3ad41680250be70bfe4c7170f41baf2
homepage   : https://github.com/stefanberger/swtpm
license    :
    - BSD-3-Clause
    - TCGL
component  : virt
summary    : TPM Emulator
description: |
    TPM emulator built on libtpms providing TPM functionality for QEMU VMs.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gnutls)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libseccomp)
    - pkgconfig(libtpms)
    - expect-devel
    - libgnutls-utils
    - socat
rundeps    :
    - libgnutls-utils
setup      : |
    %reconfigure --with-gnutls --disable-static
build      : |
    %make
install    : |
    %make_install

    # Don't ship /var/lib/swtpm-localca, create it with tmpfiles instead
    rm -rfv $installdir/var/
    install -Dm00644 $pkgfiles/swtpm.sysusers $installdir/%libdir%/sysusers.d/swtpm.conf
    install -Dm00644 $pkgfiles/swtpm.tmpfiles $installdir/%libdir%/tmpfiles.d/swtpm.conf
